a = [
  'suvyls', 'suvysl', 'suvlys', 'suvsyl', 'suvlsy', 'suvsly',
  'suyvls', 'suyvsl', 'sulvys', 'susvyl', 'sulvsy', 'susvly',
  'suylvs', 'suysvl', 'sulyvs', 'susyvl', 'sulsvy', 'suslvy',
  'suylsv', 'suyslv', 'sulysv', 'susylv', 'sulsyv', 'suslyv',
  'svuyls', 'svuysl', 'svulys', 'svusyl', 'svulsy', 'svusly',
  'syuvls', 'syuvsl', 'sluvys', 'ssuvyl', 'sluvsy', 'ssuvly',
  'syulvs', 'syusvl', 'sluyvs', 'ssuyvl', 'slusvy', 'ssulvy',
  'syulsv', 'syuslv', 'sluysv', 'ssuylv', 'slusyv', 'ssulyv',
  'svyuls', 'svyusl', 'svluys', 'svsuyl', 'svlusy', 'svsuly',
  'syvuls', 'syvusl', 'slvuys', 'ssvuyl', 'slvusy', 'ssvuly',
  'syluvs', 'sysuvl', 'slyuvs', 'ssyuvl', 'slsuvy', 'ssluvy',
  'sylusv', 'sysulv', 'slyusv', 'ssyulv', 'slsuyv', 'ssluyv',
  'svylus', 'svysul', 'svlyus', 'svsyul', 'svlsuy', 'svsluy',
  'syvlus', 'syvsul', 'slvyus', 'ssvyul', 'slvsuy', 'ssvluy',
  'sylvus', 'sysvul', 'slyvus', 'ssyvul', 'slsvuy', 'sslvuy',
  'sylsuv', 'sysluv', 'slysuv', 'ssyluv', 'slsyuv', 'sslyuv',
  'svylsu', 'svyslu', 'svlysu', 'svsylu',
  ... 620 more items
]
